### ISSUE TITLE
Modify Admin Table

### ISSUE THREAD

**Issue by yeeshuen-c** [yscccc27/OrderManagementProject#1]
### **TODO**

- [x]  addBtn(), delBtn()

- [x]  imgBtn show text

- [x]  log in page change font color
- [ ] complete exit scene (add payment?
- [ ] alert box when close window
